"""add_extract_column_to_tests

Revision ID: 54394c1ff268
Revises: 6c3a5eb2526e
Create Date: 2026-05-27 12:55:25.839798

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54394c1ff268'
down_revision: str | Sequence[str] | None = '6c3a5eb2526e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('extract', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Maps template var names to JSONPath expressions for setup tests'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'extract')
    # ### end Alembic commands ###
