"""add run_id to coverage_gaps

Revision ID: 5f9ab0bcb7aa
Revises: 836841cce315
Create Date: 2026-06-03 21:49:31.760509

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5f9ab0bcb7aa'
down_revision: str | Sequence[str] | None = '836841cce315'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coverage_gaps', sa.Column('run_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False))
    op.create_index(op.f('ix_coverage_gaps_run_id'), 'coverage_gaps', ['run_id'], unique=False)
    op.create_foreign_key(None, 'coverage_gaps', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coverage_gaps', type_='foreignkey')
    op.drop_index(op.f('ix_coverage_gaps_run_id'), table_name='coverage_gaps')
    op.drop_column('coverage_gaps', 'run_id')
    # ### end Alembic commands ###
