"""add_security_column_to_endpoints

Revision ID: 760520f2f3f0
Revises: 54394c1ff268
Create Date: 2026-05-27 13:41:40.755298

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '760520f2f3f0'
down_revision: str | Sequence[str] | None = '54394c1ff268'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('security', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment='Per-operation security requirements from OpenAPI spec'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'security')
    # ### end Alembic commands ###
