"""add coverage gaps

Revision ID: 836841cce315
Revises: aee4d216a5e3
Create Date: 2026-06-03 17:24:56.861319

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '836841cce315'
down_revision: str | Sequence[str] | None = 'aee4d216a5e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_gaps',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('test_suite_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('endpoint_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('scenario_description', sa.String(length=1024), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('spawned_test_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spawned_test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_gaps_endpoint_id'), 'coverage_gaps', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_coverage_gaps_test_suite_id'), 'coverage_gaps', ['test_suite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_gaps_test_suite_id'), table_name='coverage_gaps')
    op.drop_index(op.f('ix_coverage_gaps_endpoint_id'), table_name='coverage_gaps')
    op.drop_table('coverage_gaps')
    # ### end Alembic commands ###
