"""add_static_context_to_tests

Revision ID: c0076b8f96d0
Revises: 760520f2f3f0
Create Date: 2026-05-27 14:21:36.615057

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c0076b8f96d0'
down_revision: str | Sequence[str] | None = '760520f2f3f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('static_context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True, comment="Static variable mappings for runtime context (e.g. USER_B_ID: 'user2')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'static_context')
    # ### end Alembic commands ###
