"""add project spec endpoint models

Revision ID: f722e5dc62a3
Revises: 1bc0a243fc95
Create Date: 2026-05-20 14:19:48.168179

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f722e5dc62a3'
down_revision: str | Sequence[str] | None = '1bc0a243fc95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('target_base_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('specs',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('project_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('raw_content', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specs_project_id'), 'specs', ['project_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('spec_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['spec_id'], ['specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_spec_id'), 'endpoints', ['spec_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_spec_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_specs_project_id'), table_name='specs')
    op.drop_table('specs')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
